controller:
  motion_law_parameters:
    max_velocity: [4.0, 4.0, 4.0]
    max_acceleration: [4.5, 4.5, 4.5]
 
  cascade_controllers:
  - name: "joint1"
    inner:
      Kp: 165.7241
      Ki: 3710.0432
      Kd: 0.0
      filters_on_measure:
        - type: "NotchFilter"
          natural_frequency: 708.0
          zeros_damping: 0.1
          poles_damping: 0.8
    outer:
      Kp: 11.0
      Ki: 0.0
      Kd: 0.0
  - name: "joint2"
    inner:
      Kp: 238.1564
      Ki: 203.0739
      Kd: 0.0
      filters_on_measure:
        - type: "NotchFilter"
          natural_frequency: 594.0
          zeros_damping: 0.1
          poles_damping: 0.8
    outer:
      Kp: 20.0
      Ki: 0.0
      Kd: 0.0
  - name: "joint3"
    inner:
      Kp: 192.2866
      Ki: 351.7805
      Kd: 0.0
    outer:
      Kp: 36.0
      Ki: 0.0
      Kd: 0.0

model_parameters:
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0




